### ISSUE TITLE
Change the color of the site.

### ISSUE THREAD

**Issue by IC1101Virgo** [GingerOwls/WebDev#13]
The current site looks dull change it. To get the issue first claim it and once you are assigned only then start working.

**Comment by 99anjali** [comment]
claim

**Comment by ishantsingla18** [comment]
Hey! I am a UI designer and also a front-end developer and I can make this website look more presentable by not only changing the color but also the content placement. So, can I do this?

**Comment by IC1101Virgo** [comment]
assigned to @99anjali
